package com.demo.MoneyMap.dto.response;

import com.demo.MoneyMap.entity.enums.AlertSeverity;
import com.demo.MoneyMap.entity.enums.RuleType;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * DTO for monitoring rule response data.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Response payload containing monitoring rule information")
public class MonitoringRuleResponseDTO {

    @Schema(description = "Unique identifier of the rule", example = "1")
    private Long id;

    @Schema(description = "Name of the rule", example = "High Value Transaction")
    private String ruleName;

    @Schema(description = "Type of the rule", example = "AMOUNT_THRESHOLD")
    private RuleType ruleType;

    @Schema(description = "Rule type display name", example = "Amount Threshold")
    private String ruleTypeDisplayName;

    @Schema(description = "Alert severity", example = "HIGH")
    private AlertSeverity severity;

    @Schema(description = "Severity display name", example = "High")
    private String severityDisplayName;

    @Schema(description = "Whether the rule is active", example = "true")
    private Boolean active;

    @Schema(description = "Rule description")
    private String description;

    // Rule parameters
    @Schema(description = "Threshold amount for AMOUNT_THRESHOLD rule")
    private BigDecimal thresholdAmount;

    @Schema(description = "Currency for threshold")
    private String thresholdCurrency;

    @Schema(description = "Maximum transactions for VELOCITY rule")
    private Integer maxTransactions;

    @Schema(description = "Time window in minutes for VELOCITY rule")
    private Integer timeWindowMinutes;

    @Schema(description = "Daily limit amount for DAILY_LIMIT rule")
    private BigDecimal dailyLimitAmount;

    @Schema(description = "Lookback days for NEW_PAYEE rule")
    private Integer lookbackDays;

    @Schema(description = "Number of alerts generated by this rule")
    private Integer alertCount;

    @Schema(description = "Timestamp when the rule was created")
    private LocalDateTime createdAt;

    @Schema(description = "Timestamp when the rule was last updated")
    private LocalDateTime updatedAt;
}
