package com.demo.MoneyMap.entity;

import com.demo.MoneyMap.entity.enums.AlertSeverity;
import com.demo.MoneyMap.entity.enums.AlertStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Entity representing an alert generated by the monitoring system.
 * Tracks the alert lifecycle from creation through resolution.
 */
@Entity
@Table(name = "alerts")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Alert {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "alert_reference", unique = true, length = 50)
    private String alertReference;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rule_id", nullable = false)
    private MonitoringRule rule;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AlertSeverity severity;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private AlertStatus status = AlertStatus.OPEN;

    @Column(nullable = false, length = 500)
    private String message;

    @Column(name = "account_id", length = 50)
    private String accountId;

    @ManyToMany
    @JoinTable(
            name = "alert_transactions",
            joinColumns = @JoinColumn(name = "alert_id"),
            inverseJoinColumns = @JoinColumn(name = "payment_id")
    )
    @Builder.Default
    private Set<Payment> triggeringPayments = new HashSet<>();

    @Column(name = "acknowledged_at")
    private LocalDateTime acknowledgedAt;

    @Column(name = "acknowledged_by", length = 100)
    private String acknowledgedBy;

    @Column(name = "closed_at")
    private LocalDateTime closedAt;

    @Column(name = "closed_by", length = 100)
    private String closedBy;

    @Column(name = "resolution_notes", length = 1000)
    private String resolutionNotes;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * Add a triggering payment to this alert.
     */
    public void addTriggeringPayment(Payment payment) {
        triggeringPayments.add(payment);
    }

    /**
     * Generate an alert reference if not set.
     */
    @PrePersist
    public void generateAlertReference() {
        if (alertReference == null) {
            alertReference = "ALERT-" + System.currentTimeMillis();
        }
    }

    /**
     * Acknowledge the alert.
     */
    public void acknowledge(String acknowledgedBy) {
        this.status = AlertStatus.ACKNOWLEDGED;
        this.acknowledgedAt = LocalDateTime.now();
        this.acknowledgedBy = acknowledgedBy;
    }

    /**
     * Close the alert with resolution notes.
     */
    public void close(String closedBy, String resolutionNotes) {
        this.status = AlertStatus.CLOSED;
        this.closedAt = LocalDateTime.now();
        this.closedBy = closedBy;
        this.resolutionNotes = resolutionNotes;
    }

    /**
     * Dismiss the alert.
     */
    public void dismiss(String dismissedBy, String reason) {
        this.status = AlertStatus.DISMISSED;
        this.closedAt = LocalDateTime.now();
        this.closedBy = dismissedBy;
        this.resolutionNotes = reason;
    }
}
