package com.demo.MoneyMap.controller;

import com.demo.MoneyMap.dto.request.AlertStatusUpdateDTO;
import com.demo.MoneyMap.dto.response.AlertResponseDTO;
import com.demo.MoneyMap.dto.response.ApiResponseDTO;
import com.demo.MoneyMap.dto.response.PagedResponseDTO;
import com.demo.MoneyMap.entity.enums.AlertSeverity;
import com.demo.MoneyMap.entity.enums.AlertStatus;
import com.demo.MoneyMap.service.AlertService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

/**
 * REST Controller for Alert management operations.
 * Handles alert lifecycle from creation through resolution.
 */
@RestController
@RequestMapping("/api/v1/alerts")
@RequiredArgsConstructor
@Tag(name = "Alert Management", description = "APIs for managing transaction monitoring alerts. " +
        "Supports viewing, acknowledging, investigating, and resolving alerts generated by monitoring rules.")
public class AlertController {

    private final AlertService alertService;

    @GetMapping("/{id}")
    @Operation(summary = "Get alert by ID", description = "Retrieves alert details by its unique identifier.")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Alert found"),
            @ApiResponse(responseCode = "404", description = "Alert not found")
    })
    public ResponseEntity<ApiResponseDTO<AlertResponseDTO>> getAlertById(@PathVariable Long id) {
        AlertResponseDTO alert = alertService.getAlertById(id);
        return ResponseEntity.ok(ApiResponseDTO.success(alert));
    }

    @GetMapping("/{id}/details")
    @Operation(summary = "Get alert with full details", description = "Retrieves alert details including triggering payments and rule information.")
    public ResponseEntity<ApiResponseDTO<AlertResponseDTO>> getAlertWithDetails(@PathVariable Long id) {
        AlertResponseDTO alert = alertService.getAlertWithDetails(id);
        return ResponseEntity.ok(ApiResponseDTO.success(alert));
    }

    @GetMapping
    @Operation(summary = "Get all alerts", description = "Retrieves a paginated list of all alerts with sorting support.")
    public ResponseEntity<ApiResponseDTO<PagedResponseDTO<AlertResponseDTO>>> getAllAlerts(
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size,
            @RequestParam(defaultValue = "createdAt") String sortBy,
            @RequestParam(defaultValue = "desc") String sortDir) {
        Sort sort = sortDir.equalsIgnoreCase("desc") ? Sort.by(sortBy).descending() : Sort.by(sortBy).ascending();
        Pageable pageable = PageRequest.of(page, size, sort);
        PagedResponseDTO<AlertResponseDTO> alerts = alertService.getAllAlerts(pageable);
        return ResponseEntity.ok(ApiResponseDTO.success(alerts));
    }

    @GetMapping("/status/{status}")
    @Operation(summary = "Get alerts by status", description = "Retrieves alerts filtered by their current status. " +
            "Valid statuses: OPEN, ACKNOWLEDGED, INVESTIGATING, CLOSED, DISMISSED")
    public ResponseEntity<ApiResponseDTO<PagedResponseDTO<AlertResponseDTO>>> getAlertsByStatus(
            @PathVariable AlertStatus status,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {
        Pageable pageable = PageRequest.of(page, size, Sort.by("createdAt").descending());
        PagedResponseDTO<AlertResponseDTO> alerts = alertService.getAlertsByStatus(status, pageable);
        return ResponseEntity.ok(ApiResponseDTO.success(alerts));
    }

    @GetMapping("/severity/{severity}")
    @Operation(summary = "Get alerts by severity", description = "Retrieves alerts filtered by severity level. " +
            "Valid severities: HIGH, MEDIUM, LOW")
    public ResponseEntity<ApiResponseDTO<PagedResponseDTO<AlertResponseDTO>>> getAlertsBySeverity(
            @PathVariable AlertSeverity severity,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {
        Pageable pageable = PageRequest.of(page, size, Sort.by("createdAt").descending());
        PagedResponseDTO<AlertResponseDTO> alerts = alertService.getAlertsBySeverity(severity, pageable);
        return ResponseEntity.ok(ApiResponseDTO.success(alerts));
    }

    @GetMapping("/filter")
    @Operation(summary = "Get alerts by status and severity", description = "Retrieves alerts filtered by both status and severity.")
    public ResponseEntity<ApiResponseDTO<PagedResponseDTO<AlertResponseDTO>>> getAlertsByStatusAndSeverity(
            @RequestParam AlertStatus status,
            @RequestParam AlertSeverity severity,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {
        Pageable pageable = PageRequest.of(page, size, Sort.by("createdAt").descending());
        PagedResponseDTO<AlertResponseDTO> alerts = alertService.getAlertsByStatusAndSeverity(status, severity, pageable);
        return ResponseEntity.ok(ApiResponseDTO.success(alerts));
    }

    @GetMapping("/rule/{ruleId}")
    @Operation(summary = "Get alerts by rule", description = "Retrieves all alerts generated by a specific monitoring rule.")
    public ResponseEntity<ApiResponseDTO<PagedResponseDTO<AlertResponseDTO>>> getAlertsByRuleId(
            @PathVariable Long ruleId,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {
        Pageable pageable = PageRequest.of(page, size, Sort.by("createdAt").descending());
        PagedResponseDTO<AlertResponseDTO> alerts = alertService.getAlertsByRuleId(ruleId, pageable);
        return ResponseEntity.ok(ApiResponseDTO.success(alerts));
    }

    @GetMapping("/account/{accountId}")
    @Operation(summary = "Get alerts by account", description = "Retrieves all alerts related to a specific account.")
    public ResponseEntity<ApiResponseDTO<PagedResponseDTO<AlertResponseDTO>>> getAlertsByAccountId(
            @PathVariable String accountId,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {
        Pageable pageable = PageRequest.of(page, size, Sort.by("createdAt").descending());
        PagedResponseDTO<AlertResponseDTO> alerts = alertService.getAlertsByAccountId(accountId, pageable);
        return ResponseEntity.ok(ApiResponseDTO.success(alerts));
    }

    @GetMapping("/open/prioritized")
    @Operation(summary = "Get open alerts prioritized", description = "Retrieves open alerts sorted by severity (HIGH first) and creation time.")
    public ResponseEntity<ApiResponseDTO<List<AlertResponseDTO>>> getOpenAlertsPrioritized(
            @RequestParam(defaultValue = "20") int limit) {
        List<AlertResponseDTO> alerts = alertService.getOpenAlertsPrioritized(limit);
        return ResponseEntity.ok(ApiResponseDTO.success(alerts));
    }

    @PutMapping("/{id}/acknowledge")
    @Operation(summary = "Acknowledge an alert", description = "Acknowledges an OPEN alert, moving it to ACKNOWLEDGED status. " +
            "Indicates the alert has been seen but not yet investigated.")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Alert acknowledged successfully"),
            @ApiResponse(responseCode = "400", description = "Alert is not in OPEN status"),
            @ApiResponse(responseCode = "404", description = "Alert not found")
    })
    public ResponseEntity<ApiResponseDTO<AlertResponseDTO>> acknowledgeAlert(
            @PathVariable Long id,
            @RequestParam(defaultValue = "System") String operatorName) {
        AlertResponseDTO alert = alertService.acknowledgeAlert(id, operatorName);
        return ResponseEntity.ok(ApiResponseDTO.success(alert, "Alert acknowledged successfully"));
    }

    @PutMapping("/{id}/status")
    @Operation(summary = "Update alert status", description = "Updates the status of an alert. Validates that the transition is allowed. " +
            "Valid transitions: OPEN→ACKNOWLEDGED/DISMISSED, ACKNOWLEDGED→INVESTIGATING/DISMISSED, INVESTIGATING→CLOSED/DISMISSED")
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Status updated successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid status transition"),
            @ApiResponse(responseCode = "404", description = "Alert not found")
    })
    public ResponseEntity<ApiResponseDTO<AlertResponseDTO>> updateAlertStatus(
            @PathVariable Long id,
            @Valid @RequestBody AlertStatusUpdateDTO updateDTO) {
        AlertResponseDTO alert = alertService.updateAlertStatus(id, updateDTO);
        return ResponseEntity.ok(ApiResponseDTO.success(alert, "Alert status updated successfully"));
    }

    @PostMapping("/{id}/notes")
    @Operation(summary = "Add resolution notes", description = "Adds or updates resolution notes for an alert.")
    public ResponseEntity<ApiResponseDTO<AlertResponseDTO>> addResolutionNotes(
            @PathVariable Long id,
            @RequestParam String notes) {
        AlertResponseDTO alert = alertService.addResolutionNotes(id, notes);
        return ResponseEntity.ok(ApiResponseDTO.success(alert, "Notes added successfully"));
    }

    @GetMapping("/statistics")
    @Operation(summary = "Get alert statistics", description = "Returns statistics about alerts including counts by status, severity, and average response times.")
    public ResponseEntity<ApiResponseDTO<Map<String, Object>>> getAlertStatistics() {
        Map<String, Object> statistics = alertService.getAlertStatistics();
        return ResponseEntity.ok(ApiResponseDTO.success(statistics));
    }

    @GetMapping("/count/{status}")
    @Operation(summary = "Get alert count by status", description = "Returns the count of alerts in a specific status.")
    public ResponseEntity<ApiResponseDTO<Long>> getAlertCountByStatus(@PathVariable AlertStatus status) {
        long count = alertService.countAlertsByStatus(status);
        return ResponseEntity.ok(ApiResponseDTO.success(count));
    }
}
